<?xml version="1.0"?>
<package format="3">
  <name>k9_ros2_nav</name>
  <version>0.1.0</version>
  <description>K9 navigation sensors and commissioning launch configuration.</description>
  <maintainer email="hopkira@googlemail.com">Richard Hopkins</maintainer>
  <license>TODO</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>ldlidar_component</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
